import type { Metadata } from "next";
import "./globals.css";
import { Euphoria_Script } from "next/font/google";
import localFont from "next/font/local";

export const cherish = Euphoria_Script({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cherish",
});

export const patrickOklahoma = localFont({
  src: [
    {
      path: "../public/fonts/PatrickOklahoma-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-patrick-oklahoma",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hr">
      <body className={`${cherish.variable} ${patrickOklahoma.variable}`}>
        {children}
      </body>
    </html>
  );
}
